# Generated by Django 3.0.5 on 2020-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serail', models.CharField(max_length=20)),
                ('belongs_to', models.CharField(max_length=20)),
                ('installed_at', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=20)),
                ('person_name', models.CharField(max_length=20)),
                ('CC_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
