# Generated by Django 3.0.5 on 2020-05-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200427_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('belongs', models.CharField(max_length=30)),
                ('enduser', models.CharField(max_length=30)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
