# Generated by Django 3.0.5 on 2020-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20200504_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('dept', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('belongs', models.CharField(max_length=20)),
                ('enduser', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=20)),
                ('CC_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='allotment',
        ),
        migrations.RenameField(
            model_name='pc_stock',
            old_name='serail',
            new_name='serial',
        ),
    ]
