# Generated by Django 3.0.5 on 2020-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200505_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=20)),
                ('hostName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('brand', models.IntegerField()),
                ('model', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('IPAdress', models.GenericIPAddressField(unique=True)),
                ('warrantyEnd', models.DateField()),
                ('other_comments', models.CharField(max_length=20)),
            ],
        ),
    ]
